server:
  port: 8080
  context-path: /CYVoteServer

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cyvoteserver?serverTimezone=UTC
    username: root
    password: QAZqaz!23
    driver-class-name: com.mysql.cj.jdbc.Driver